import Link from "next/link";

export const metadata = {
  title: "Data & security — Cash-Flow Forecaster",
  description:
    "How Cash-Flow Forecaster handles, protects, and stores your financial data.",
};

export default function PrivacyPage() {
  return (
    <main className="doc-page">
      <div className="doc-inner">
        <Link href="/" className="doc-back">
          ← Back to forecaster
        </Link>

        <h1>Data &amp; security</h1>
        <p className="doc-lead">
          This tool works with sensitive financial information. Here is exactly
          what we collect, how it is protected, and the control you have over it.
        </p>

        <h2>What we store</h2>
        <ul>
          <li>
            <strong>Your account</strong> — email address and a one-way{" "}
            <em>bcrypt</em> hash of your password. We never store your password in
            plain text and cannot recover it.
          </li>
          <li>
            <strong>Ledgers &amp; forecasts</strong> — the cash-flow figures you
            upload or generate, plus saved scenarios, so you can reopen past runs.
          </li>
          <li>
            <strong>Counterparty names</strong> — customer and vendor labels on
            invoices and bills are <strong>encrypted at rest</strong> with
            AES-based Fernet encryption before they are written to the database.
          </li>
          <li>
            <strong>Activity log</strong> — security-relevant events (sign-in,
            registration, creating or deleting saved data) are recorded so you can
            review account activity.
          </li>
        </ul>

        <h2>How it is protected</h2>
        <ul>
          <li>
            <strong>Encryption in transit.</strong> All traffic is served over
            HTTPS/TLS.
          </li>
          <li>
            <strong>Encryption at rest.</strong> Sensitive free-text fields are
            encrypted with a key held only in the server environment, separate
            from the database.
          </li>
          <li>
            <strong>Authentication.</strong> Access is protected by signed JWT
            tokens; every request that reads or writes your data is scoped to your
            account only.
          </li>
          <li>
            <strong>Isolation.</strong> Your runs, scenarios, invoices, and bills
            are never visible to other users.
          </li>
        </ul>

        <h2>Your activity log</h2>
        <p>
          When signed in, your recent account activity is available from the API
          at <code>/api/auth/me/audit</code>. It lists actions taken on your
          account with timestamps, so you can spot anything unexpected.
        </p>

        <h2>Third parties</h2>
        <p>
          Optional AI briefings are generated by a large-language-model provider
          using only the numeric summary of your forecast. Optional Slack alerts
          send threshold notifications to a webhook you configure. Both are off
          unless you enable them.
        </p>

        <h2>Data deletion</h2>
        <p>
          You can delete individual saved scenarios and clear your run history at
          any time from the app. To remove your account entirely, contact the
          operator of your deployment.
        </p>

        <p className="doc-note">
          This page describes the current behaviour of the application and is not
          a legal contract. For production use, pair it with your own privacy
          policy and terms.
        </p>
      </div>
    </main>
  );
}
