"""Pluggable LLM provider layer.

The briefing can be generated by Gemini, OpenAI, or Anthropic. Selection is
driven by config (``LLM_PROVIDER``) and available API keys. For each provider a
curated, best-first list of models is tried until one succeeds, so the app
always uses the best *available* model without hard-coding a single name — and
you can switch vendors just by setting a different key / ``LLM_PROVIDER``.

The provider never invents data: it is handed a finished, structured brief and
asked only to phrase it. Grounding is enforced one layer up in ``narrative``.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from app.config import Settings, get_settings

_SYSTEM = (
    "You are a precise FP&A analyst. You will receive a JSON brief of "
    "already-computed cash-flow forecast figures. Write a concise, factual "
    "3-4 sentence briefing for a CFO. Rules: (1) Only state numbers that appear "
    "in the brief. (2) Never invent figures, percentages, or dates not present. "
    "(3) No hedging fluff, no emojis, no markdown headings. Plain prose."
)

# Order used when LLM_PROVIDER=auto: the first provider with a key wins.
_AUTO_ORDER = ("gemini", "anthropic", "openai")

# Best-first model preferences per provider. The list is tried in order and the
# first model that responds is used, so accounts without the newest model fall
# back automatically. Override entirely by setting the matching *_MODEL env var.
_PREFERRED_MODELS: dict[str, tuple[str, ...]] = {
    "gemini": ("gemini-2.5-flash", "gemini-2.0-flash", "gemini-2.0-flash-lite", "gemini-1.5-flash"),
    "openai": ("gpt-4o", "gpt-4.1", "gpt-4.1-mini", "gpt-4o-mini"),
    "anthropic": (
        "claude-opus-4-5",
        "claude-sonnet-4-5",
        "claude-3-5-sonnet-latest",
        "claude-3-5-haiku-latest",
    ),
}


class LLMUnavailable(RuntimeError):
    """Raised when no configured provider/model could produce a briefing."""


# Backwards-compatible alias (older callers imported this name).
GeminiUnavailable = LLMUnavailable


@dataclass(frozen=True)
class LLMResult:
    text: str
    provider: str
    model: str


# --- Per-vendor call implementations ---------------------------------------
# Each returns the generated text or raises on any failure (auth, network,
# unknown model, empty response). Import errors surface a clear install hint.


def _call_gemini(model: str, prompt: str, api_key: str) -> str:
    try:
        from google import genai as google_genai
    except ImportError as exc:
        raise LLMUnavailable("google-genai not installed (pip install google-genai).") from exc
    client = google_genai.Client(api_key=api_key)
    resp = client.models.generate_content(
        model=model,
        contents=prompt,
        config={"system_instruction": _SYSTEM, "temperature": 0.2},
    )
    return (resp.text or "").strip()


def _call_openai(model: str, prompt: str, api_key: str) -> str:
    try:
        from openai import OpenAI
    except ImportError as exc:  # pragma: no cover - import guard
        raise LLMUnavailable("openai not installed (pip install openai).") from exc
    client = OpenAI(api_key=api_key)
    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": _SYSTEM},
            {"role": "user", "content": prompt},
        ],
        temperature=0.2,
    )
    return (resp.choices[0].message.content or "").strip()


def _call_anthropic(model: str, prompt: str, api_key: str) -> str:
    try:
        import anthropic
    except ImportError as exc:  # pragma: no cover - import guard
        raise LLMUnavailable("anthropic not installed (pip install anthropic).") from exc
    client = anthropic.Anthropic(api_key=api_key)
    resp = client.messages.create(
        model=model,
        system=_SYSTEM,
        max_tokens=400,
        temperature=0.2,
        messages=[{"role": "user", "content": prompt}],
    )
    parts = [b.text for b in resp.content if getattr(b, "type", None) == "text"]
    return "".join(parts).strip()


@dataclass(frozen=True)
class _Vendor:
    name: str
    key_attr: str
    model_attr: str
    call: Callable[[str, str, str], str]


_VENDORS: dict[str, _Vendor] = {
    "gemini": _Vendor("gemini", "gemini_api_key", "gemini_model", _call_gemini),
    "openai": _Vendor("openai", "openai_api_key", "openai_model", _call_openai),
    "anthropic": _Vendor("anthropic", "anthropic_api_key", "anthropic_model", _call_anthropic),
}


def _models_for(vendor: _Vendor, settings: Settings) -> tuple[str, ...]:
    override = getattr(settings, vendor.model_attr, "").strip()
    if override:
        return (override,)
    return _PREFERRED_MODELS[vendor.name]


def _resolve_chain(settings: Settings) -> list[_Vendor]:
    """Ordered list of vendors to try, honoring LLM_PROVIDER and available keys."""
    choice = settings.llm_provider.lower().strip()
    if choice in _VENDORS:
        vendor = _VENDORS[choice]
        has_key = bool(getattr(settings, vendor.key_attr, "").strip())
        return [vendor] if has_key else []
    # "auto" (or anything unrecognized): every keyed vendor, in priority order.
    return [
        _VENDORS[name]
        for name in _AUTO_ORDER
        if getattr(settings, _VENDORS[name].key_attr, "").strip()
    ]


def describe() -> dict[str, str | None]:
    """Report the provider/model that *would* be used, without making a call."""
    settings = get_settings()
    if settings.llm_provider.lower().strip() == "none":
        return {"provider": None, "model": None}
    chain = _resolve_chain(settings)
    if not chain:
        return {"provider": None, "model": None}
    vendor = chain[0]
    return {"provider": vendor.name, "model": _models_for(vendor, settings)[0]}


def generate(prompt: str) -> LLMResult:
    """Generate a briefing, trying providers/models until one succeeds.

    Raises :class:`LLMUnavailable` if nothing is configured or every attempt
    fails, so the caller can fall back to the deterministic template.
    """
    settings = get_settings()
    if settings.llm_provider.lower().strip() == "none":
        raise LLMUnavailable("LLM disabled (LLM_PROVIDER=none).")

    chain = _resolve_chain(settings)
    if not chain:
        raise LLMUnavailable("No LLM provider configured (set an API key).")

    errors: list[str] = []
    for vendor in chain:
        api_key = getattr(settings, vendor.key_attr).strip()
        for model in _models_for(vendor, settings):
            try:
                text = vendor.call(model, prompt, api_key)
                if text:
                    return LLMResult(text=text, provider=vendor.name, model=model)
                errors.append(f"{vendor.name}/{model}: empty response")
            except LLMUnavailable:
                raise
            except Exception as exc:  # noqa: BLE001 - normalize provider errors
                errors.append(f"{vendor.name}/{model}: {exc}")
                continue
    raise LLMUnavailable("; ".join(errors) or "All LLM attempts failed.")

